package com.fortunekidew.pewaa.models;

import java.util.Date;

import io.realm.RealmObject;
import io.realm.annotations.PrimaryKey;

/**
 * Created by mwakima on 10/8/16.
 */

public class PaymentModel extends RealmObject {
    @PrimaryKey
    private String id;

    private String wishlist_item_id;

    private String user_id;

    private String status;

    private String reference;

    private String description;

    private float amount;

    private Date created_on;

    private Date updated_on;

    // Standard getters & setters generated by your IDE…
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }
}
